server:
  port: 8093

spring:
  application:
    name: payment-web

dubbo:
  application:
    name: payment-web
    qos-port: 32222
  protocol:
    name: dubbo
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
    use-as-config-center: false
    parameters:
      namespace: 11f0da81-888c-429e-8053-76695dfea77c
