server:
  port: 8085

spring:
  application:
    name: checkout-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/checkout?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

dubbo:
  application:
    name: checkout-server
  protocol:
    name: dubbo
    port: 20895
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
    use-as-config-center: false
    parameters:
      namespace: 11f0da81-888c-429e-8053-76695dfea77c